---
- name: Test AWX
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    netbox_api_url: "http://137.184.18.229:8000/api/dcim/devices/"
    netbox_api_token: "4560d44e6a2c66a8a703947d204eed2d671c6da4"
    
  tasks:
    - name: Netbox API GET request
      uri:
        url: "{{ netbox_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
      register: netbox_response

    - name: Filter jcp
      set_fact:
        filtered_devices_jcp: "{{ netbox_response.json.results | selectattr('device_role.name', 'equalto', 'jcp') | list }}"

    - name: Create data_result list
      set_fact:
        data_result: "{{ data_result | default([]) + [{'id': item.id, 'name': item.name, 'custom_fields': {'ntp_config': item.custom_fields.ntp_config | default({})}}] }}"
      loop: "{{ filtered_devices_jcp }}"

    - name: Display data_result as JSON without verbose ansible log
      debug:
        var: data_result
      verbosity: 0
      no_log: true
      ansible_verbose_always: false
      ansible_no_log: null
