---
- name: Test AWX
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    netbox_api_url: "http://137.184.18.229:8000/api/dcim/devices/"
    netbox_api_token: "4560d44e6a2c66a8a703947d204eed2d671c6da4"
    output_directory: "/Users/networkingdevdeveloper/Desktop/output"  # Ruta del directorio de salida
    output_file: "{{ output_directory }}/data_result.json"  # Ruta completa del archivo de salida
    

    
  tasks:       
    - name: Netbox API GET request
      uri:
        url: "{{ netbox_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
      register: netbox_response

    - name: Filter jcp
      set_fact:
        filtered_devices_jcp: "{{ netbox_response.json.results | selectattr('device_role.name', 'equalto', 'jcp') | list }}"

    - name: Check current date
      command: date +"%Y-%m-%d"
      register: current_date
      changed_when: false

    - name: Create data_result list
      set_fact:
        data_result: "{{ data_result | default([]) + [{'id': item.id, 'name': item.name, 'custom_fields': {'ntp_config': item.custom_fields.ntp_config | default({})}, 'created': item.created, 'last_updated': item.last_updated, 'new_device': item.created | regex_search(current_date.stdout) is not none}] }}"
      loop: "{{ filtered_devices_jcp }}"
      loop_control:
        loop_var: item

    - name: Save file JSON
      copy:
        content: "{{ data_result | to_nice_json }}"
        dest: "{{ output_file }}"

