---
- name: Test AWX
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    netbox_api_url: "http://137.184.18.229:8000/api/dcim/devices/"
    netbox_api_token: "4560d44e6a2c66a8a703947d204eed2d671c6da4"
    
  tasks:       
    - name: Netbox API GET request
      uri:
        url: "{{ netbox_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
      register: netbox_response

    - name: Filter jcp
      set_fact:
        filtered_devices_jcp: "{{ netbox_response.json.results | selectattr('device_role.name', 'equalto', 'jcp') | list }}"


    - name: Format required
      set_fact:
        formatted_devices: "{{ filtered_devices_jcp | map(attribute='ansible_facts') | map('combine', {'new_device': false}) | map('combine', {'id': item.id, 'name': item.name, 'custom_fields': item.custom_fields, 'created': item.created, 'last_updated': item.last_updated}) | list }}"
      loop: "{{ filtered_devices_jcp }}"
      loop_control:
        loop_var: item

    - name: Display NTP Configuration
      debug:
        var: formatted_devices
    
