---
- name: Test AWX
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    netbox_api_url: "http://137.184.18.229:8000/api/dcim/devices/"
    netbox_api_token: "4560d44e6a2c66a8a703947d204eed2d671c6da4"
    
  
  tasks:       
    - name: Netbox API GET request
      uri:
        url: "{{ netbox_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
      register: netbox_response

    - name: Filter jcp
      set_fact:
        filtered_devices_jcp: "{{ netbox_response.json.results | selectattr('device_role.name', 'equalto', 'jcp') | list }}"

    - name: Filter ntp config
      set_fact:
        filtered_device_with_ntp: "{{ filtered_devices_jcp | first }}"
        ntp_config: "{{ filtered_device_with_ntp.custom_fields.ntp_config | default({}) }}"

    - name: Display NTP Configuration
      debug:
        var: ntp_config
   
